/**
 * Author：zhoushuanglong
 * Time：2017/7/27
 * Description：index constants
 */

// 登陆
export const LOGIN = 'login'

// 面包屑
export const BREADCRUMB = 'breadcrumb'

// 获取选定数据(跳转用)
export const GETITEM = 'getItem'

// 登录弹框展示用
export const ALERTLOGIN = 'alertLogin'

// 导航
export const NAVIGATION = 'navigation'

// 频道
export const CHANNELLIST = 'channelList'

// 频道
export const FLASHTYPELIST = 'flashTypeList'

// 城市
export const ACTIVITYCITY = 'cityList'

// 游戏列表
export const GAMELIST = 'game-list'

// 后台管理员账号管理
export const MANAGERACCOUNT = {
    'ADD_DATA': 'ADD_MANAGERACCOUNT_DATA',
    'ADD_QUERY': 'ADD_MANAGERACCOUNT_QUERY',
    'EDIT_USER_INFO': 'ADD_MANAGERACCOUNT_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_MANAGERACCOUNT_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_MANAGERACCOUNT_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_MANAGERACCOUNT_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_MANAGERACCOUNT_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_MANAGERACCOUNT_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_MANAGERACCOUNT_FILTER_DATA'
}

// 选中数据
export const SELECTEDDATA = 'SELECTED_DATA'

// 量化的常量
// 合作伙伴管理
export const PARTNER = {
    'ADD_DATA': 'ADD_PARTNER_DATA',
    'ADD_QUERY': 'ADD_PARTNER_QUERY',
    'EDIT_USER_INFO': 'ADD_PARTNER_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_PARTNER_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_PARTNER_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_PARTNER_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_PARTNER_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_PARTNER_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_PARTNER_FILTER_DATA'
}
// 委员会管理
export const COUNCIL = {
    'ADD_DATA': 'ADD_COUNCIL_DATA',
    'ADD_QUERY': 'ADD_COUNCIL_QUERY',
    'EDIT_USER_INFO': 'ADD_COUNCIL_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_COUNCIL_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_COUNCIL_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_COUNCIL_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_COUNCIL_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_COUNCIL_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_COUNCIL_FILTER_DATA'
}
// 队伍管理
export const TEAM = {
    'ADD_DATA': 'ADD_TEAM_DATA',
    'ADD_QUERY': 'ADD_TEAM_QUERY',
    'EDIT_USER_INFO': 'ADD_TEAM_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_TEAM_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_TEAM_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_TEAM_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_TEAM_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_TEAM_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_TEAM_FILTER_DATA'
}

// pc/M 端banner轮播管理
export const BANNER = {
    'ADD_DATA': 'ADD_BANNER_DATA',
    'MORE_DATA': 'MORE_BANNER_DATA',
    'ADD_QUERY': 'ADD_BANNER_QUERY',
    'EDIT_USER_INFO': 'ADD_BANNER_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_BANNER_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_BANNER_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_BANNER_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_BANNER_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_BANNER_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_BANNER_FILTER_DATA',
    'GET_TOP_NUM': 'GET_TOP_NUM'
}

// 账号管理
export const ACCOUNT = {
    'ADD_DATA': 'ADD_ACCOUNT_DATA',
    'ADD_QUERY': 'ADD_ACCOUNT_QUERY',
    'EDIT_USER_INFO': 'ADD_ACCOUNT_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_ACCOUNT_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_ACCOUNT_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_ACCOUNT_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_ACCOUNT_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_ACCOUNT_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_ACCOUNT_FILTER_DATA'
}
