/**
 * Author：zhoushuanglong
 * Time：2017/7/27
 * Description：index constants
 */

// 登陆
export const LOGIN = 'login'

// 面包屑
export const BREADCRUMB = 'breadcrumb'

// 获取选定数据(跳转用)
export const GETITEM = 'getItem'

// 登录弹框展示用
export const ALERTLOGIN = 'alertLogin'

// 导航
export const NAVIGATION = 'navigation'

// 频道
export const CHANNELLIST = 'channelList'

// 频道
export const FLASHTYPELIST = 'flashTypeList'

// 城市
export const ACTIVITYCITY = 'cityList'

// 游戏列表
export const GAMELIST = 'game-list'

// 后台管理员账号管理
export const MANAGERACCOUNT = {
    'ADD_DATA': 'ADD_MANAGERACCOUNT_DATA',
    'ADD_QUERY': 'ADD_MANAGERACCOUNT_QUERY',
    'EDIT_USER_INFO': 'ADD_MANAGERACCOUNT_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_MANAGERACCOUNT_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_MANAGERACCOUNT_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_MANAGERACCOUNT_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_MANAGERACCOUNT_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_MANAGERACCOUNT_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_MANAGERACCOUNT_FILTER_DATA'
}

// 快讯推送
export const FLASHPUSH = {
    'ADD_DATA': 'ADD_FLASHPUSH_DATA',
    'ADD_QUERY': 'ADD_FLASHPUSH_QUERY',
    'EDIT_USER_INFO': 'ADD_FLASHPUSH_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_FLASHPUSH_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_FLASHPUSH_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_FLASHPUSH_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_FLASHPUSH_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_FLASHPUSH_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_FLASHPUSH_FILTER_DATA'
}

// 后台简单数据统计
export const COUNT = {
    'ADD_DATA': 'ADD_COUNT_DATA',
    'ADD_QUERY': 'ADD_COUNT_QUERY',
    'EDIT_USER_INFO': 'ADD_COUNT_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_COUNT_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_COUNT_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_COUNT_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_COUNT_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_COUNT_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_COUNT_FILTER_DATA'
}

// 新闻阅读量统计
export const NEWSREADCOUNT = {
    'ADD_DATA': 'ADD_NEWSREADCOUNT_DATA',
    'ADD_QUERY': 'ADD_NEWSREADCOUNT_QUERY',
    'EDIT_USER_INFO': 'ADD_NEWSREADCOUNT_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_NEWSREADCOUNT_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_NEWSREADCOUNT_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_NEWSREADCOUNT_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_NEWSREADCOUNT_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_NEWSREADCOUNT_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_NEWSREADCOUNT_FILTER_DATA'
}

// 新闻管理
export const POST = {
    'ADD_DATA': 'ADD_POST_DATA',
    'ADD_QUERY': 'ADD_POST_QUERY',
    'EDIT_USER_INFO': 'ADD_POST_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_POST_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_POST_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_POST_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_POST_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_POST_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_POST_FILTER_DATA'
}

// 小程序文章管理
export const MINIAPP = {
    'ADD_DATA': 'ADD_MINIAPP_DATA',
    'ADD_QUERY': 'ADD_MINIAPP_QUERY',
    'EDIT_USER_INFO': 'ADD_MINIAPP_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_MINIAPP_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_MINIAPP_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_MINIAPP_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_MINIAPP_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_MINIAPP_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_MINIAPP_FILTER_DATA'
}

// 活动发布管理
export const ACTIVITYPUBLISH = {
    'ADD_DATA': 'ADD_ACTIVITYPUBLISH_DATA',
    'ADD_QUERY': 'ADD_ACTIVITYPUBLISH_QUERY',
    'EDIT_USER_INFO': 'ADD_ACTIVITYPUBLISH_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_ACTIVITYPUBLISH_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_ACTIVITYPUBLISH_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_ACTIVITYPUBLISH_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_ACTIVITYPUBLISH_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_ACTIVITYPUBLISH_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_ACTIVITYPUBLISH_FILTER_DATA'
}

// 视频管理
export const VIDEO = {
    'ADD_DATA': 'ADD_VIDEO_DATA',
    'ADD_QUERY': 'ADD_VIDEO_QUERY',
    'EDIT_USER_INFO': 'ADD_VIDEO_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_VIDEO_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_VIDEO_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_VIDEO_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_VIDEO_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_VIDEO_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_VIDEO_FILTER_DATA'
}

// 视频审核
export const VIDEOAUDIT = {
    'ADD_DATA': 'ADD_VIDEOAUDIT_DATA',
    'ADD_QUERY': 'ADD_VIDEOAUDIT_QUERY',
    'EDIT_USER_INFO': 'ADD_VIDEOAUDIT_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_VIDEOAUDIT_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_VIDEOAUDIT_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_VIDEOAUDIT_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_VIDEOAUDIT_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_VIDEOAUDIT_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_VIDEOAUDIT_FILTER_DATA'
}

// 小程序视频管理
export const MINIVIDEO = {
    'ADD_DATA': 'ADD_MINIVIDEO_DATA',
    'ADD_QUERY': 'ADD_MINIVIDEO_QUERY',
    'EDIT_USER_INFO': 'ADD_MINIVIDEO_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_MINIVIDEO_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_MINIVIDEO_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_MINIVIDEO_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_MINIVIDEO_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_MINIVIDEO_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_MINIVIDEO_FILTER_DATA'
}

// 新闻频道
export const CHANNEL = {
    'ADD_DATA': 'ADD_CHANNEL_DATA',
    'ADD_QUERY': 'ADD_CHANNEL_QUERY',
    'EDIT_USER_INFO': 'ADD_CHANNEL_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_CHANNEL_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_CHANNEL_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_CHANNEL_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_CHANNEL_SEARCH_QUERY',
    'SET_FILTER_DATA': 'SET_CHANNEL_FILTER_DATA',
    'SET_PAGE_DATA': 'SET_CHANNEL_PAGE_DATA'
}

// 活动城市
export const CITY = {
    'ADD_DATA': 'ADD_CITY_DATA',
    'ADD_QUERY': 'ADD_CITY_QUERY',
    'EDIT_USER_INFO': 'ADD_CITY_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_CITY_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_CITY_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_CITY_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_CITY_SEARCH_QUERY',
    'SET_FILTER_DATA': 'SET_CITY_FILTER_DATA',
    'SET_PAGE_DATA': 'SET_CITY_PAGE_DATA'
}

// 审核新闻
export const ARTICLEAUDIT = {
    'ADD_DATA': 'ADD_ARTICLEAUDIT_DATA',
    'ADD_QUERY': 'ADD_ARTICLEAUDIT_QUERY',
    'EDIT_USER_INFO': 'ADD_ARTICLEAUDIT_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_ARTICLEAUDIT_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_ARTICLEAUDIT_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_ARTICLEAUDIT_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_ARTICLEAUDIT_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_ARTICLEAUDIT_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_ARTICLEAUDIT_FILTER_DATA'
}

// ICO 管理
export const ICO = {
    'ADD_DATA': 'ADD_ICO_DATA',
    'ADD_QUERY': 'ADD_ICO_QUERY',
    'EDIT_USER_INFO': 'ADD_ICO_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_ICO_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_ICO_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_ICO_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_ICO_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_ICO_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_ICO_FILTER_DATA'
}

// 直播管理
export const LIVE = {
    'ADD_DATA': 'ADD_LIVE_DATA',
    'ADD_QUERY': 'ADD_LIVE_QUERY',
    'EDIT_USER_INFO': 'ADD_LIVE_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_LIVE_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_LIVE_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_LIVE_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_LIVE_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_LIVE_PAGE_DATA',
    'GET_ZCR_LIST': 'GET_ZCR_LIST',
    'GET_GUEST_LIST': 'GET_GUEST_LIST',
    'SET_FILTER_DATA': 'SET_LIVE_FILTER_DATA'
}

// 直播内容管理
export const LIVECONTENT = {
    'ADD_DATA': 'ADD_LIVECONTENT_DATA',
    'MORE_DATA': 'MORE_LIVECONTENT_DATA',
    'ADD_QUERY': 'ADD_LIVECONTENT_QUERY',
    'EDIT_USER_INFO': 'ADD_LIVECONTENT_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_LIVECONTENT_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_LIVECONTENT_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_LIVECONTENT_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_LIVECONTENT_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_LIVECONTENT_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_LIVECONTENT_FILTER_DATA',
    'INSERT_LIVE': 'INSERT_CONTENT_LIVE'
}

// 直播用户管理
export const LIVEUSER = {
    'ADD_DATA': 'ADD_LIVEUSER_DATA',
    'ADD_QUERY': 'ADD_LIVEUSER_QUERY',
    'EDIT_USER_INFO': 'ADD_LIVEUSER_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_LIVEUSER_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_LIVEUSER_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_LIVEUSER_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_LIVEUSER_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_LIVEUSER_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_LIVEUSER_FILTER_DATA'
}

// STO嘉宾用户管理
export const STOUSER = {
    'ADD_DATA': 'ADD_STOUSER_DATA',
    'ADD_QUERY': 'ADD_STOUSER_QUERY',
    'EDIT_USER_INFO': 'ADD_STOUSER_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_STOUSER_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_STOUSER_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_STOUSER_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_STOUSER_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_STOUSER_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_STOUSER_FILTER_DATA'
}

// notice
export const STONOTICE = {
    'ADD_DATA': 'ADD_STONOTICE_DATA',
    'ADD_QUERY': 'ADD_STONOTICE_QUERY',
    'EDIT_USER_INFO': 'ADD_STONOTICE_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_STONOTICE_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_STONOTICE_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_STONOTICE_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_STONOTICE_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_STONOTICE_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_STONOTICE_FILTER_DATA'
}

// pc专题内容管理
export const SPECIALTOPIC = {
    'ADD_DATA': 'ADD_SPECIALTOPIC_DATA',
    'MORE_DATA': 'MORE_SPECIALTOPIC_DATA',
    'ADD_QUERY': 'ADD_SPECIALTOPIC_QUERY',
    'EDIT_USER_INFO': 'ADD_SPECIALTOPIC_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_SPECIALTOPIC_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_SPECIALTOPIC_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_SPECIALTOPIC_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_SPECIALTOPIC_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_SPECIALTOPIC_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_SPECIALTOPIC_FILTER_DATA',
    'GET_TOP_NUM': 'GET_TOP_NUM'
}

// app专题内容管理
export const APPTOPIC = {
    'ADD_DATA': 'ADD_APPTOPIC_DATA',
    'MORE_DATA': 'MORE_APPTOPIC_DATA',
    'ADD_QUERY': 'ADD_APPTOPIC_QUERY',
    'EDIT_USER_INFO': 'ADD_APPTOPIC_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_APPTOPIC_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_APPTOPIC_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_APPTOPIC_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_APPTOPIC_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_APPTOPIC_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_APPTOPIC_FILTER_DATA',
    'GET_TOP_NUM': 'GET_TOP_NUM'
}

// pc/M 端banner轮播管理
export const BANNER = {
    'ADD_DATA': 'ADD_BANNER_DATA',
    'MORE_DATA': 'MORE_BANNER_DATA',
    'ADD_QUERY': 'ADD_BANNER_QUERY',
    'EDIT_USER_INFO': 'ADD_BANNER_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_BANNER_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_BANNER_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_BANNER_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_BANNER_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_BANNER_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_BANNER_FILTER_DATA',
    'GET_TOP_NUM': 'GET_TOP_NUM'
}

// 专题活动内容管理
export const ACTIVITY = {
    'ADD_DATA': 'ADD_ACTIVITY_DATA',
    'MORE_DATA': 'MORE_ACTIVITY_DATA',
    'ADD_QUERY': 'ADD_ACTIVITY_QUERY',
    'EDIT_USER_INFO': 'ADD_ACTIVITY_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_ACTIVITY_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_ACTIVITY_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_ACTIVITY_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_ACTIVITY_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_ACTIVITY_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_ACTIVITY_FILTER_DATA',
    'GET_TOP_NUM': 'GET_TOP_NUM'
}
// 专栏作者管理
export const COLUMNAUTHOR = {
    'ADD_DATA': 'ADD_COLUMNAUTHOR_DATA',
    'MORE_DATA': 'MORE_COLUMNAUTHOR_DATA',
    'ADD_QUERY': 'ADD_COLUMNAUTHOR_QUERY',
    'EDIT_USER_INFO': 'ADD_COLUMNAUTHOR_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_COLUMNAUTHOR_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_COLUMNAUTHOR_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_COLUMNAUTHOR_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_COLUMNAUTHOR_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_COLUMNAUTHOR_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_COLUMNAUTHOR_FILTER_DATA',
    'GET_TOP_NUM': 'GET_TOP_NUM'
}
// 新闻聚合管理
export const NEWSMERGE = {
    'ADD_DATA': 'ADD_NEWSMERGE_DATA',
    'MORE_DATA': 'MORE_NEWSMERGE_DATA',
    'ADD_QUERY': 'ADD_NEWSMERGE_QUERY',
    'EDIT_USER_INFO': 'ADD_NEWSMERGE_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_NEWSMERGE_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_NEWSMERGE_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_NEWSMERGE_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_NEWSMERGE_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_NEWSMERGE_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_NEWSMERGE_FILTER_DATA'
}

// 帖子管理
export const COMMENT = {
    'ADD_DATA': 'ADD_COMMENT_DATA',
    'ADD_QUERY': 'ADD_COMMENT_QUERY',
    'EDIT_USER_INFO': 'ADD_COMMENT_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_COMMENT_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_COMMENT_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_COMMENT_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_COMMENT_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_COMMENT_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_COMMENT_FILTER_DATA'
}

// 快讯管理
export const FLASH = {
    'ADD_DATA': 'ADD_FLASH_DATA',
    'ADD_QUERY': 'ADD_FLASH_QUERY',
    'EDIT_USER_INFO': 'ADD_FLASH_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_FLASH_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_FLASH_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_FLASH_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_FLASH_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_FLASH_PAGE_DATA'
}

// 快讯类型管理
export const FLASHTYPE = {
    'ADD_DATA': 'ADD_FLASHTYPE_DATA',
    'ADD_QUERY': 'ADD_FLASHTYPE_QUERY',
    'EDIT_USER_INFO': 'ADD_FLASHTYPE_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_FLASHTYPE_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_FLASHTYPE_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_FLASHTYPE_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_FLASHTYPE_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_FLASHTYPE_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_FLASHTYPE_FILTER_DATA'
}

// 快讯管理
export const FLASHAUDIT = {
    'ADD_DATA': 'ADD_FLASHAUDIT_DATA',
    'ADD_QUERY': 'ADD_FLASHAUDIT_QUERY',
    'EDIT_USER_INFO': 'ADD_FLASHAUDIT_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_FLASHAUDIT_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_FLASHAUDIT_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_FLASHAUDIT_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_FLASHAUDIT_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_FLASHAUDIT_PAGE_DATA'
}

// 发帖子用户管理
export const USERPOST = {
    'ADD_DATA': 'ADD_USERPOST_DATA',
    'ADD_QUERY': 'ADD_USERPOST_QUERY',
    'EDIT_USER_LIST_ITEM': 'EDIT_USER_LIST_ITEM',
    'EDIT_USER_POST_LIST_ITEM': 'EDIT_USER_POST_LIST_ITEM',
    'EDIT_COMMENT_LIST_ITEM': 'EDIT_COMMENT_LIST_ITEM',
    'DEL_USER_POST_LIST_ITEM': 'DEL_USER_POST_LIST_ITEM',
    'DEL_COMMENT_LIST_ITEM': 'DEL_COMMENT_LIST_ITEM',
    'SET_SEARCH_QUERY': 'SET_USER_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_USER_PAGE_DATA',
    'SET_POST_LIST_PAGE_DATA': 'SET_USER_POST_LIST_PAGE_DATA',
    'SET_COMMENT_LIST_PAGE_DATA': 'SET_USER_COMMENT_LIST_PAGE_DATA'
}

// 广告管理
export const AD = {
    'ADD_DATA': 'ADD_AD_DATA',
    'ADD_QUERY': 'ADD_AD_QUERY',
    'EDIT_USER_INFO': 'ADD_AD_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_AD_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_AD_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_AD_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_AD_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_AD_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_AD_FILTER_DATA'
}

// 广告数据管理
export const ADDATA = {
    'ADD_DATA': 'ADD_ADDATA_DATA',
    'ADD_QUERY': 'ADD_ADDATA_QUERY',
    'EDIT_USER_INFO': 'ADD_ADDATA_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_ADDATA_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_ADDATA_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_ADDATA_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_ADDATA_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_ADDATA_PAGE_DATA',
    'SET_PAGE_DETAIL_DATA': 'SET_PAGE_DETAIL_DATA'
}

// 返回管理
export const FEEDBACK = {
    'ADD_DATA': 'ADD_FEEDBACK_DATA',
    'ADD_QUERY': 'ADD_FEEDBACK_QUERY',
    'EDIT_USER_INFO': 'ADD_FEEDBACK_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_FEEDBACK_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_FEEDBACK_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_FEEDBACK_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_FEEDBACK_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_FEEDBACK_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_FEEDBACK_FILTER_DATA'
}

// 身份认证审核
export const AUDIT = {
    'ADD_DATA': 'ADD_AUDIT_DATA',
    'ADD_QUERY': 'ADD_AUDIT_QUERY',
    'EDIT_USER_INFO': 'ADD_AUDIT_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_AUDIT_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_AUDIT_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_AUDIT_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_AUDIT_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_AUDIT_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_AUDIT_FILTER_DATA'
}

// 官方身份认证
export const OFFICIALAUDIT = {
    'ADD_DATA': 'ADD_OFFICIALAUDIT_DATA',
    'ADD_QUERY': 'ADD_OFFICIALAUDIT_QUERY',
    'EDIT_USER_INFO': 'ADD_OFFICIALAUDIT_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_OFFICIALAUDIT_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_OFFICIALAUDIT_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_OFFICIALAUDIT_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_OFFICIALAUDIT_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_OFFICIALAUDIT_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_OFFICIALAUDIT_FILTER_DATA'
}

// 图片鉴别
export const IMGS = {
    'ADD_DATA': 'ADD_IMGS_DATA',
    'EDIT_SELECT_DATA': 'EDIT_IMGS_SELECT_DATA',
    'EDIT_LIST_ITEM': 'EDIT_IMGS_LIST_ITEM'
}

// 词条管理
export const LANGUAGE = {
    'ADD_DATA': 'ADD_LANGUAGE_DATA',
    'ADD_QUERY': 'ADD_LANGUAGE_QUERY',
    'EDIT_LIST_ITEM': 'EDIT_LANGUAGE_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_LANGUAGE_LIST_ITEM',
    'EDIT_REPEAT_LIST_ITEM': 'EDIT_LANGUAGE_REPEAT_LIST_ITEM',
    'SELECT_REPEAT_LIST_ITEM': 'SELECT_LANGUAGE_REPEAT_LIST_ITEM'
}

// 游戏初始化
export const INITGAME = {
    'ADD_DATA': 'ADD_INITGAME_DATA',
    'ADD_QUERY': 'ADD_INITGAME_QUERY',
    'EDIT_LIST_ITEM': 'EDIT_INITGAME_LIST_ITEM'
}

// 用户权限
export const AUTHORITY = {
    'ADD_DATA': 'ADD_AUTHORITY_DATA',
    'ADD_QUERY': 'ADD_AUTHORITY_QUERY',
    'EDIT_LIST_ITEM': 'EDIT_AUTHORITY_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_AUTHORITY_LIST_ITEM'
}

// 选中数据
export const SELECTEDDATA = 'SELECTED_DATA'

// 账号管理
// 快讯账号管理
export const FLASHACCOUNT = {
    'ADD_DATA': 'ADD_FLASHACCOUNT_DATA',
    'ADD_QUERY': 'ADD_FLASHACCOUNT_QUERY',
    'EDIT_USER_INFO': 'ADD_FLASHACCOUNT_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_FLASHACCOUNT_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_FLASHACCOUNT_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_FLASHACCOUNT_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_FLASHACCOUNT_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_FLASHACCOUNT_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_FLASHACCOUNT_FILTER_DATA'
}

// 新闻账号管理
export const POSTACCOUNT = {
    'ADD_DATA': 'ADD_POSTACCOUNT_DATA',
    'ADD_QUERY': 'ADD_POSTACCOUNT_QUERY',
    'EDIT_USER_INFO': 'ADD_POSTACCOUNT_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_POSTACCOUNT_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_POSTACCOUNT_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_POSTACCOUNT_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_POSTACCOUNT_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_POSTACCOUNT_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_POSTACCOUNT_FILTER_DATA'
}

// 黑名单管理
export const BLACKLIST = {
    'INIT_DATA': 'INIT_BLACKLIST_DATA',
    'ADD_BLACKLIST': 'ADD_BLACKLIST',
    'REMOVE_BLACKLIST': 'REMOVE_BLACKLIST',
    'SET_SEARCH_RESULT': 'SET_BLACKLIST_SEARCH_RESULT',
    'SET_PAGE_DATA': 'SET_BLACKLIST_PAGE_DATA'
}

// 推荐币种管理
export const COINRECOMMEND = {
    'ADD_DATA': 'ADD_COINRECOMMEND_DATA',
    'ADD_QUERY': 'ADD_COINRECOMMEND_QUERY',
    'EDIT_USER_INFO': 'ADD_COINRECOMMEND_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_COINRECOMMEND_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_COINRECOMMEND_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_COINRECOMMEND_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_COINRECOMMEND_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_COINRECOMMEND_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_COINRECOMMEND_FILTER_DATA'
}

// 手机引导页币种管理
export const APPOPENCOINRECOMMEND = {
    'ADD_DATA': 'ADD_APPOPENCOINRECOMMEND_DATA',
    'ADD_QUERY': 'ADD_APPOPENCOINRECOMMEND_QUERY',
    'EDIT_USER_INFO': 'ADD_APPOPENCOINRECOMMEND_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_APPOPENCOINRECOMMEND_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_APPOPENCOINRECOMMEND_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_APPOPENCOINRECOMMEND_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_APPOPENCOINRECOMMEND_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_APPOPENCOINRECOMMEND_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_APPOPENCOINRECOMMEND_FILTER_DATA'
}

// 推荐交易所管理
export const EXCHANGERECOMMEND = {
    'ADD_DATA': 'ADD_EXCHANGERECOMMEND_DATA',
    'ADD_QUERY': 'ADD_EXCHANGERECOMMEND_QUERY',
    'EDIT_USER_INFO': 'ADD_EXCHANGERECOMMEND_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_EXCHANGERECOMMEND_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_EXCHANGERECOMMEND_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_EXCHANGERECOMMEND_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_EXCHANGERECOMMEND_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_EXCHANGERECOMMEND_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_EXCHANGERECOMMEND_FILTER_DATA'
}

// 网页推荐币种管理
export const WEBCOINRECOMMEND = {
    'ADD_DATA': 'ADD_WEBCOINRECOMMEND_DATA',
    'ADD_QUERY': 'ADD_WEBCOINRECOMMEND_QUERY',
    'EDIT_USER_INFO': 'ADD_WEBCOINRECOMMEND_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_WEBCOINRECOMMEND_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_WEBCOINRECOMMEND_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_WEBCOINRECOMMEND_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_WEBCOINRECOMMEND_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_WEBCOINRECOMMEND_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_WEBCOINRECOMMEND_FILTER_DATA'
}

// 热门币种管理
export const HOTCOIN = {
    'ADD_DATA': 'ADD_HOTCOIN_DATA',
    'ADD_QUERY': 'ADD_HOTCOIN_QUERY',
    'EDIT_USER_INFO': 'ADD_HOTCOIN_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_HOTCOIN_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_HOTCOIN_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_HOTCOIN_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_HOTCOIN_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_HOTCOIN_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_HOTCOIN_FILTER_DATA'
}

// 版本通知管理
export const VERSION = {
    'ADD_DATA': 'ADD_VERSION_DATA',
    'ADD_QUERY': 'ADD_VERSION_QUERY',
    'EDIT_USER_INFO': 'ADD_VERSION_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_VERSION_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_VERSION_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_VERSION_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_VERSION_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_VERSION_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_VERSION_FILTER_DATA'
}

// 热门标签和作者管理
export const HOTAUTHORANDTAGS = {
    'ADD_DATA': 'ADD_HOTAUTHORANDTAGS_DATA',
    'ADD_QUERY': 'ADD_HOTAUTHORANDTAGS_QUERY',
    'EDIT_USER_INFO': 'ADD_HOTAUTHORANDTAGS_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_HOTAUTHORANDTAGS_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_HOTAUTHORANDTAGS_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_HOTAUTHORANDTAGS_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_HOTAUTHORANDTAGS_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_HOTAUTHORANDTAGS_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_HOTAUTHORANDTAGS_FILTER_DATA'
}

// 热门币种管理
export const NEWSHOTWORDS = {
    'ADD_DATA': 'ADD_NEWSHOTWORDS_DATA',
    'ADD_QUERY': 'ADD_NEWSHOTWORDS_QUERY',
    'EDIT_USER_INFO': 'ADD_NEWSHOTWORDS_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_NEWSHOTWORDS_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_NEWSHOTWORDS_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_NEWSHOTWORDS_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_NEWSHOTWORDS_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_NEWSHOTWORDS_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_NEWSHOTWORDS_FILTER_DATA'
}

// 词语过滤管理
export const WORDSFILTER = {
    'ADD_DATA': 'ADD_WORDSFILTER_DATA',
    'ADD_QUERY': 'ADD_WORDSFILTER_QUERY',
    'EDIT_USER_INFO': 'ADD_WORDSFILTER_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_WORDSFILTER_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_WORDSFILTER_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_WORDSFILTER_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_WORDSFILTER_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_WORDSFILTER_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_WORDSFILTER_FILTER_DATA'
}

// 底部当行信息列表
export const COOPERATION = {
    'INIT_COOPERATION': 'INIT_COOPERATION',
    'GET_HOT_TAG_LIST': 'GET_HOT_TAG_LIST',
    'ADD_COOPERATION': 'ADD_COOPERATION',
    'DEL_COOPERATION': 'DEL_COOPERATION',
    'EDIT_COOPERATION': 'EDIT_COOPERATION',
    'SEARCH_COOPERATION': 'SEARCH_COOPERATION',
    'SET_PAGE_DATA': 'SET_COOPERATION_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_FILTER_DATA',
    'SET_FORM_DATA': 'SET_FORM_DATA'
}

// 火星中国行管理
export const MARSTRIP = {
    'ADD_DATA': 'ADD_MARSTRIP_DATA',
    'ADD_QUERY': 'ADD_MARSTRIP_QUERY',
    'EDIT_USER_INFO': 'ADD_MARSTRIP_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_MARSTRIP_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_MARSTRIP_LIST_ITEM',
    'SET_SEARCH_QUERY': 'SET_MARSTRIP_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_MARSTRIP_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_MARSTRIP_FILTER_DATA'
}

// 火星中国行注册人员
export const REGISTRANT = {
    'ADD_DATA': 'ADD_REGISTRANT_DATA',
    'ADD_QUERY': 'ADD_REGISTRANT_QUERY',
    'EDIT_USER_INFO': 'ADD_REGISTRANT_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_REGISTRANT_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_REGISTRANT_LIST_ITEM',
    'SET_SEARCH_QUERY': 'SET_REGISTRANT_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_REGISTRANT_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_REGISTRANT_FILTER_DATA'
}

// STO参加人员
export const PARTICIPATE = {
    'ADD_DATA': 'ADD_PARTICIPATE_DATA',
    'ADD_QUERY': 'ADD_PARTICIPATE_QUERY',
    'EDIT_USER_INFO': 'ADD_PARTICIPATE_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_PARTICIPATE_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_PARTICIPATE_LIST_ITEM',
    'SET_SEARCH_QUERY': 'SET_PARTICIPATE_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_PARTICIPATE_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_PARTICIPATE_FILTER_DATA'
}

// 社交媒体twitter管理
export const TWITTER = {
    'ADD_DATA': 'ADD_TWITTER_DATA',
    'MORE_DATA': 'MORE_TWITTER_DATA',
    'ADD_QUERY': 'ADD_TWITTER_QUERY',
    'EDIT_USER_INFO': 'ADD_TWITTER_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_TWITTER_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_TWITTER_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_TWITTER_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_TWITTER_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_TWITTER_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_TWITTER_FILTER_DATA',
    'GET_TOP_NUM': 'GET_TOP_NUM'
}

export const TWITTERACCOUNT = {
    'ADD_DATA': 'ADD_TWITTERACCOUNT_DATA',
    'ADD_QUERY': 'ADD_TWITTERACCOUNT_QUERY',
    'EDIT_USER_INFO': 'ADD_TWITTERACCOUNT_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_TWITTERACCOUNT_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_TWITTERACCOUNT_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_TWITTERACCOUNT_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_TWITTERACCOUNT_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_TWITTERACCOUNT_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_TWITTERACCOUNT_FILTER_DATA'
}

// 量化的常量
// 合作伙伴管理
export const PARTNER = {
    'ADD_DATA': 'ADD_PARTNER_DATA',
    'ADD_QUERY': 'ADD_PARTNER_QUERY',
    'EDIT_USER_INFO': 'ADD_PARTNER_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_PARTNER_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_PARTNER_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_PARTNER_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_PARTNER_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_PARTNER_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_PARTNER_FILTER_DATA'
}
// 委员会管理
export const COUNCIL = {
    'ADD_DATA': 'ADD_COUNCIL_DATA',
    'ADD_QUERY': 'ADD_COUNCIL_QUERY',
    'EDIT_USER_INFO': 'ADD_COUNCIL_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_COUNCIL_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_COUNCIL_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_COUNCIL_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_COUNCIL_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_COUNCIL_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_COUNCIL_FILTER_DATA'
}
// 队伍管理
export const TEAM = {
    'ADD_DATA': 'ADD_TEAM_DATA',
    'ADD_QUERY': 'ADD_TEAM_QUERY',
    'EDIT_USER_INFO': 'ADD_TEAM_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_TEAM_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_TEAM_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_TEAM_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_TEAM_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_TEAM_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_TEAM_FILTER_DATA'
}
